#!/usr/bin/env bash
set -euo pipefail

PROJECT_ROOT="/Volumes/ORICO/quant_pj1"
cd "${PROJECT_ROOT}"

mkdir -p runtime_state/discord_jobs /tmp/matplotlib

export MPLCONFIGDIR="${MPLCONFIGDIR:-/tmp/matplotlib}"
export DISCORD_DRY_RUN="${DISCORD_DRY_RUN:-0}"
export DISCORD_ENABLE_SCAN_EXECUTION="${DISCORD_ENABLE_SCAN_EXECUTION:-1}"
export AG_TOP_DEEP_N="${AG_TOP_DEEP_N:-10}"
export AG_TOP_DEEP_WRITE_DB="${AG_TOP_DEEP_WRITE_DB:-1}"
export AG_KR_DAILY_PHASE="${AG_KR_DAILY_PHASE:-confirmed}"
export AG_KR_DAILY_SCAN_ENGINE="${AG_KR_DAILY_SCAN_ENGINE:-kis_operational}"
export AG_KR_DAILY_LEGACY_FALLBACK="${AG_KR_DAILY_LEGACY_FALLBACK:-1}"
export AG_KR_DAILY_LEGACY_SHADOW="${AG_KR_DAILY_LEGACY_SHADOW:-0}"
export AG_KIS_OPERATIONAL_PREFILTER="${AG_KIS_OPERATIONAL_PREFILTER:-1}"
export AG_KIS_PREFILTER_MAX_CANDIDATES="${AG_KIS_PREFILTER_MAX_CANDIDATES:-80}"
export AG_KIS_PREFILTER_RANK_LIMIT="${AG_KIS_PREFILTER_RANK_LIMIT:-80}"
export AG_KIS_OPERATIONAL_SCAN_WORKERS="${AG_KIS_OPERATIONAL_SCAN_WORKERS:-4}"
export AG_KIS_OPERATIONAL_SCAN_RETRIES="${AG_KIS_OPERATIONAL_SCAN_RETRIES:-1}"
export AG_KIS_OPERATIONAL_PIPELINE_TIMEOUT_SEC="${AG_KIS_OPERATIONAL_PIPELINE_TIMEOUT_SEC:-0}"

exec /usr/bin/env python3 -u multi_agent/tools/run_kr_daily_auto_scans.py --phase "${AG_KR_DAILY_PHASE}"
